language: groovy
jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
  - gem install compass
  - npm install

script:
  - cd grails-app/assets/stylesheets
  - compass compile
  - cd ../../..
  - ./grailsw package
  - ./grailsw war

